#
# Change the following line to configure the bamboo logging levels (one of INFO, DEBUG, ERROR, FATAL)
#
status = warn
rootLogger = INFO, console, filelog

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{DEFAULT} %p [%t] [%c{1}] %bambooEscapedMessage%n
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = DEBUG

#using 'bamboo home aware' appender. If the File is relative a relative Path the file goes into {bamboo.home}/logs
appender.filelog.type = BambooRollingFile
appender.filelog.name = filelog
appender.filelog.fileName = atlassian-bamboo.log
appender.filelog.filePattern = atlassian-bamboo.log.%i
appender.filelog.layout.type = PatternLayout
appender.filelog.layout.pattern = %d{DEFAULT} %p [%t] [%c{1}] %bambooEscapedMessage%n
appender.filelog.policies.type = Policies
appender.filelog.policies.size.type = SizeBasedTriggeringPolicy
appender.filelog.policies.size.size = 100MB
appender.filelog.strategy.type = DefaultRolloverStrategy
appender.filelog.strategy.max = 5
appender.filelog.strategy.fileIndex = min

########################################################################################################################
# Access Log
########################################################################################################################
#using 'bamboo home aware' appender for access logs
appender.accesslog.type = BambooRollingFile
appender.accesslog.name = accesslog
appender.accesslog.fileName = atlassian-bamboo-access.log
appender.accesslog.filePattern = atlassian-bamboo-access.log.%i
appender.accesslog.layout.type = PatternLayout
appender.accesslog.layout.pattern = %d{DEFAULT} %p [%t] [%c{1}] %bambooEscapedMessage%n
appender.accesslog.policies.type = Policies
appender.accesslog.policies.size.type = SizeBasedTriggeringPolicy
appender.accesslog.policies.size.size = 20MB
appender.accesslog.strategy.type = DefaultRolloverStrategy
appender.accesslog.strategy.max = 5
appender.accesslog.strategy.fileIndex = min

logger.accesslogfilter = INFO, accesslog, console
logger.accesslogfilter.name = com.atlassian.bamboo.filter.AccessLogFilter
logger.accesslogfilter.additivity = false

########################################################################################################################
# Emergency, high volume logging
########################################################################################################################
appender.emergency.type = BambooRollingFile
appender.emergency.name = emergency
appender.emergency.fileName = emergency-atlassian-bamboo.log
appender.emergency.filePattern = emergency-atlassian-bamboo.log.%i
appender.emergency.layout.type = PatternLayout
appender.emergency.layout.pattern = %d{DEFAULT} %p [%t] [%c{1}] %bambooEscapedMessage%n
appender.emergency.policies.type = Policies
appender.emergency.policies.size.type = SizeBasedTriggeringPolicy
appender.emergency.policies.size.size = 20480KB
appender.emergency.strategy.type = DefaultRolloverStrategy
appender.emergency.strategy.max = 5
appender.emergency.strategy.fileIndex = min

logger.emergency=INFO, emergency
logger.emergency.name = emergency
logger.emergency.additivity = false

########################################################################################################################
# Javascript Debugging
########################################################################################################################
appender.javascript.type = BambooRollingFile
appender.javascript.name = javascript
appender.javascript.fileName = js-atlassian-bamboo.log
appender.javascript.filePattern = js-atlassian-bamboo.log.%i
appender.javascript.layout.type = PatternLayout
appender.javascript.layout.pattern = %d{DEFAULT} %p [%t] [%c{1}] %bambooEscapedMessage%n
appender.javascript.policies.type = Policies
appender.javascript.policies.size.type = SizeBasedTriggeringPolicy
appender.javascript.policies.size.size = 20480KB
appender.javascript.strategy.type = DefaultRolloverStrategy
appender.javascript.strategy.max = 5
appender.javascript.strategy.fileIndex = min

logger.javascript=DEBUG, javascript
logger.javascript.name = JavaScript
logger.javascript.additivity = false

########################################################################################################################
# Database Logging
########################################################################################################################
logger.SessionImpl.level=ERROR
logger.SessionImpl.name=org.hibernate.impl.SessionImpl
#Remove when criteria queries are mostly gone
logger.hibernate-deprecation.level=ERROR
logger.hibernate-deprecation.name=org.hibernate.orm.deprecation
#Remove when most entities are on annotations instead of hbms
logger.MetadataContext.level=ERROR
logger.MetadataContext.name=org.hibernate.metamodel.internal.MetadataContext

## log hibernate prepared statements/SQL queries (equivalent to setting 'hibernate.show_sql' to 'true')
#logger.sql.name = org.hibernate.SQL
#logger.sql.level= DEBUG

## log hibernate prepared statement parameter values
#logger.hibernate-type.name=org.hibernate.type
#logger.hibernate-type.level=TRACE
#logger.hibernate-batcher.name=org.hibernate.impl.BatcherImpl
#logger.hibernate-batcher.level=DEBUG

## log active objects sql statements
#logger.ao-sql.name=net.java.ao.sql
#logger.ao-sql.level=DEBUG

## Bamboo plan cache detailed logging
#logger.plan-cache.name=com.atlassian.bamboo.plan.cache
#logger.plan-cache.level= DEBUG

########################################################################################################################
# OSGi and Atl plugins related logs
########################################################################################################################
logger.FelixOsgiContainerManager.level=WARN
logger.FelixOsgiContainerManager.name = com.atlassian.plugin.osgi.container.felix.FelixOsgiContainerManager
logger.ExportPackageListBuilder.level=ERROR
logger.ExportPackageListBuilder.name = org.twdata.pkgscanner.ExportPackageListBuilder
logger.atlassian-plugin.level=WARN
logger.atlassian-plugin.name = com.atlassian.plugin
logger.streams.level=WARN
logger.streams.name=com.atlassian.streams

########################################################################################################################
# SSH proxy related settings
########################################################################################################################
logger.sshd.level=WARN
logger.sshd.name=org.apache.sshd
logger.plugin-ssh.level=WARN
logger.plugin-ssh.name = com.atlassian.bamboo.plugins.ssh
logger.bamboo-ssh.level=WARN
logger.bamboo-ssh.name=com.atlassian.bamboo.ssh
logger.bamboo-crypto.level=ERROR
logger.bamboo-crypto.name=com.atlassian.bamboo.crypto
logger.bamboo-crypto-instance.level=INFO
logger.bamboo-crypto-instance.name=com.atlassian.bamboo.crypto.instance
logger.bamboo-crypto-bouncy-castle-provider-utils.level=INFO
logger.bamboo-crypto-bouncy-castle-provider-utils.name=com.atlassian.bamboo.crypto.BouncyCastleProviderUtils

########################################################################################################################
# General ignore logging for various packages
########################################################################################################################
logger.marketplaceClient.level = WARN
logger.marketplaceClient.name = com.atlassian.marketplace.client.MarketplaceClient
logger.webwork.level=WARN
logger.webwork.name = webwork
logger.velocity.level=WARN
logger.velocity.name = velocity
logger.xwork-util.level = ERROR
logger.xwork-util.name = com.opensymphony.xwork2.util
logger.springframework.level = WARN
logger.springframework.name = org.springframework
logger.hibernate.level = WARN
logger.hibernate.name = org.hibernate
logger.acegi.level = WARN
logger.acegi.name = org.acegisecurity
logger.activemq-failover.level = WARN
logger.activemq-failover.name = org.apache.activemq.transport.failover.FailoverTransport
logger.servlet-filter.level = WARN
logger.servlet-filter.name = com.atlassian.plugin.servlet.filter.ServletFilterModuleContainerFilter
logger.plugin-resource-download.level = WARN
logger.plugin-resource-download.name = com.atlassian.plugin.servlet.PluginResourceDownload
logger.less-web-resource-transformer.level = ERROR
logger.less-web-resource-transformer.name = com.atlassian.plugins.less.LessWebResourceTransformer
logger.dependency-resolver.level = ERROR
logger.dependency-resolver.name = com.atlassian.plugin.webresource.DefaultResourceDependencyResolver
logger.apache.level = INFO
logger.apache.name = org.apache
logger.botocss.level = WARN
logger.botocss.name = com.atlassian.botocss
logger.amazonaws.level = WARN
logger.amazonaws.name = com.amazonaws
logger.amazonaws-ec2metadatautils.level = ERROR
logger.amazonaws-ec2metadatautils.name = com.amazonaws.util.EC2MetadataUtils
logger.amazonaws-instancemetadataservice.level = ERROR
logger.amazonaws-instancemetadataservice.name = com.amazonaws.internal.InstanceMetadataServiceResourceFetcher
logger.vutbr-web.level = WARN
logger.vutbr-web.name = cz.vutbr.web
logger.oauth-serviceprovider.level = WARN
logger.oauth-serviceprovider.name = com.atlassian.oauth.serviceprovider.internal

# Embedded Crowd
logger.crowd.level = WARN
logger.crowd.name = com.atlassian.crowd
logger.recoveryModeService.level = INFO
logger.recoveryModeService.name = com.atlassian.crowd.manager.recovery.SystemPropertyRecoveryModeService


# log S3 retries
logger.s3.name=com.amazonaws.services.s3
logger.s3.level=INFO

# net.schmizz.sshj
logger.sshj.name=net.schmizz.sshj
logger.sshj.level=WARN

logger.struts2-beanselection.name=org.apache.struts2.config.BeanSelectionProvide
logger.struts2-beanselection.level=WARN

logger.tunnel.name=com.atlassian.tunnel
logger.tunnel.level=WARN

# Docker client
logger.docker.name=com.spotify.docker.client
logger.docker.level = WARN

# profiling (needs system property -Datlassian.profile.activate=true to be activated)
logger.profiling.name=com.atlassian.util.profiling
logger.profiling.level=DEBUG

#upm cache flushes
logger.upm-stacktrace.name=com.atlassian.cache.stacktrace
logger.upm-stacktrace.level=WARN

# ephemeral agents
logger.ephemeral-agents.name=com.atlassian.bamboo.agent.ephemeral
logger.ephemeral-agents.level=INFO
logger.ephemeral-agents-kubernetesexecutor.name=com.atlassian.bamboo.agent.ephemeral.KubernetesExecutor
logger.ephemeral-agents-kubernetesexecutor.level=INFO
