ARG BASE_IMAGE=ksb-bamboo-agent:6.8.0
FROM $BASE_IMAGE

LABEL maintainer="hello@windtunnel.io"

# Switch to root user to install package system wide

USER root

# Install Docker CLI

RUN apt-get update && \
    apt-get -y install apt-transport-https \
      ca-certificates \
      curl \
      gnupg2 \
      software-properties-common && \
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
    add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
      $(lsb_release -cs) \
      stable" && \
   apt-get update && \
   apt-get -y install docker-ce-cli

# Switch back to Bamboo user

USER ${BAMBOO_USER}
