ARG BASE_IMAGE=ksb-bamboo-agent:nix-6.8.0
FROM $BASE_IMAGE

LABEL maintainer="hello@windtunnel.io"

ARG BAMBOO_SERVER

# Pre-warm the Agent

ENV BAMBOO_PREWARM_DIR=${BAMBOO_USER_HOME}/prewarm

COPY --chown=$BAMBOO_USER:$BAMBOO_GROUP scripts/prewarm-agent.sh prewarm-agent.sh
RUN chmod +x ./prewarm-agent.sh
RUN ./prewarm-agent.sh

RUN rm -f ./prewarm-agent.log
RUN rm -f ./prewarm-agent.sh

# Override runAgent

COPY --chown=$BAMBOO_USER:$BAMBOO_GROUP scripts/run-agent-prewarm.sh run-agent.sh
